data_params:
  num_frames: 5
  time_window: 1
  uniform_time_sample: true
  in_csv: null
  tag2class: null
  in_csv_infer: "./data/valid_fold_0.csv"
  datapath: "./data/video_dataset_processed"

args:
  batch_size: 64

stages: null
callbacks_params:
  loader:
    callback: CheckpointCallback
  infer:
    callback: InferCallback
