model_params:
  fp16: false
  model: tsn

  base_model:
    partial_bn: null
    arch: resnet18
    pretrained: true
    frozen: true
    pooling: GlobalConcatPool2d

  tsn_model:
    feature_net_hiddens: 128
    emb_net_hiddens: 128
    consensus: ["avg", "max", "attention"]
    n_cls: &n_cls 4
    activation_fn: ReLU
    norm_fn: BatchNorm1d
    bias: false
    dropout: 0.5

args:
  expdir: "tsn"
  logdir: /mnt/ssd1/logs/tsn
#  baselogdir: /mnt/ssd1/logs/tsn_grid # for grid search

stages:
  state_params:
    main_metric: precision01
    minimize_metric: false

  criterion_params:
    criterion: BCELoss # CrossEntropyLoss

  data_params:
    batch_size: 16
    n_frames: 5
    time_window: 1
    uniform_time_sample: true
    tag2class: "./data/labeling.json"
    tag_column: "video"
    class_column: "class"
    datapath: "/mnt/ssd1/datasets/video_dataset_processed"
    in_csv_train: "./data/train_fold_0.csv"
    in_csv_valid: "./data/val_fold_0.csv"
    in_csv_infer: "./data/val_fold_0.csv"
    one_hot_classes: *n_cls
    num_workers: 16

  callbacks_params:
    loss:
      callback: LossCallback
      input_key: targets_onehot

    optimizer:
      callback: OptimizerCallback

    precision:
      callback: PrecisionCallback
      precision_args: [1]

    scheduler:
      callback: SchedulerCallback
      reduce_metric: precision01

    saver:
      callback: CheckpointCallback

    tflogger:
      callback: TensorboardLogger

    infer:
      callback: InferCallback

  stage_head_train:
    state_params:
      num_epochs: 10

    optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0005

    scheduler_params:
      scheduler: MultiStepLR
      gamma: 0.5
      milestones: [5]

  stage_full_finetune:
    stage_params:
      partial_bn: 2
      num_epochs: 20

    optimizer_params:
      optimizer: SGD
      momentum: 0.9
      lr: 0.001
      weight_decay: 0.0005

    scheduler_params:
      scheduler: MultiStepLR
      gamma: 0.1
      milestones: [10]
